name: test

on:
  push:
    branches:
      - develop
      - main
  pull_request:

permissions:
  contents: read

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"
          check-latest: true
          cache: false

      - name: Run unit tests
        run: |
          make test
